export enum Language {
  ABYSSAL = 'Abyssal',
  ALL = 'all',
  ALL_IN_LIFE = 'all languages it knew in life',
  ANY_IN_LIFE = 'any languages it knew in life',
  AURAN = 'Auran',
  COMMON = 'Common',
  DEEP_SPEECH = 'Deep Speech',
  DRACONIC = 'Draconic',
  ELVISH = 'Elvish',
  GIANT = 'Giant',
  GOBLIN = 'Goblin',
  IGNAN = 'Ignan',
  INFERNAL = 'Infernal',
  ORC = 'Orc',
  TERRAN = 'Terran',
  UNDERCOMMON = 'Undercommon',
}
