name: Build app for GH Pages
on:
  push:
    branches:
      - master
jobs:
  compile-source-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull changes from master
        id: pull-changes
        run: |
          git config --global user.email "dungeon.masters.tracker@bot.com"
          git config --global user.name "Dungeon Masters Tracker Bot"

          git checkout ghpages
          git pull
          git rebase origin/master
      - name: Build Application
        id: build-application
        if: steps.pull-changes.outcome == 'success'
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - name: Move compiled files to docs folder
        id: move-compiled-files
        if: steps.build-application.outcome == 'success'
        run: |
          rm -rf ./docs
          mkdir ./docs
          mv ./dist/dungeon-masters-tracker/* ./docs/
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update compiled app"
          git push origin ghpages --force
